version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
    timezone: US/Central
  ignore:
  - dependency-name: cypress
    versions:
    - 6.5.0
